import { TypeSafeClient, noul } from "@typesafe-ai/sdk";

let client;

function getClient() {
  if (!client) {
    client = new TypeSafeClient();
  }
  return client;
}

const AI_DETECTION_QUESTION = noul(
  "Judge whether `text` was generated by an AI language model rather than written " +
    "by a human. Weigh signs of AI generation - generic, evenly-paced phrasing; " +
    "formulaic structure (e.g. tidy rule-of-three lists, symmetric paragraphs); " +
    "hedging and overly balanced framing; absence of specific personal detail or " +
    "lived experience; unnaturally consistent tone and grammar throughout - against " +
    "signs of human writing - typos or grammatical slips; irregular structure and " +
    "pacing; concrete anecdotes, names, or numbers; informal or idiosyncratic " +
    "phrasing; strong, unhedged opinions; a distinct personal voice.",
  {
    true: "The text was generated, or substantially drafted, by an AI language model.",
    false: "The text was written by a human, without substantial AI generation.",
  },
);

function verdictFor(aiProbability) {
  if (aiProbability >= 0.85) return "likely_ai";
  if (aiProbability >= 0.6) return "possibly_ai";
  if (aiProbability >= 0.4) return "uncertain";
  if (aiProbability >= 0.15) return "possibly_human";
  return "likely_human";
}

/**
 * Score a piece of text for how likely it is to be AI-generated vs. human-written.
 * @param {string} text
 */
export async function detectText(text) {
  const { answers, model } = await getClient().systemOne({
    state: { text },
    questions: { aiGenerated: AI_DETECTION_QUESTION },
  });

  const aiProbability = answers.aiGenerated.noul;
  const humanProbability = 1 - aiProbability;

  return {
    aiProbability,
    humanProbability,
    aiScore: Math.round(aiProbability * 100),
    humanScore: Math.round(humanProbability * 100),
    verdict: verdictFor(aiProbability),
    model,
  };
}

export { verdictFor };
